ci(gha): Inline scripts
Signed-off-by: Peter Mikus <pmikus@cisco.com>

diff --git a/.github/workflows/vpp-checkstyle.yml b/.github/workflows/vpp-checkstyle.yml
--- a/.github/workflows/vpp-checkstyle.yml
+++ b/.github/workflows/vpp-checkstyle.yml
@@ -96,23 +96,77 @@ jobs:
 
       - name: Run Checkstyle Scripts
         run: |
-          .github/scripts/checkstyle.sh
+          LINE="*******************************************************************"
+          BUILD_EXT_DIR="build/external"
+          MATRIX_FILE="$BUILD_EXT_DIR/mlx_rdma_dpdk_matrix.txt"
+          PKGS_DIR="$BUILD_EXT_DIR/packages"
+          if git show --stat | grep -q "$MATRIX_FILE" ; then
+              RDMA_CORE_VERSION="$(grep rdma-core_version $PKGS_DIR/rdma-core.mk | grep -v '(' | mawk '{print $3}')"
+              DPDK_VERSION="$(grep dpdk_version $PKGS_DIR/dpdk.mk | grep -v '(' | mawk '{print $3}')"
+              CURRENT_MATRIX="rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION"
+              if grep -q "$CURRENT_MATRIX" "$MATRIX_FILE"; then
+                  echo -e "$LINE\n* DPDK/RDMA-CORE matrix file update successfully verified\n$LINE"
+              else
+                  echo -e "$LINE\n* ERROR: 'rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION' not found in $MATRIX_FILE!\n$LINE"
+                  exit 1
+              fi
+          fi
+
+          if grep -qE '^checkstyle:' Makefile
+          then
+              make UNATTENDED=yes install-deps checkstyle
+          else
+              echo "Can't find checkstyle target in Makefile - skipping checkstyle"
+          fi
 
       - name: Run Test Checkstyle Scripts
         run: |
-          .github/scripts/test_checkstyle.sh
+          if [ -n "$(grep -E '^test-checkstyle:' Makefile)" ]
+          then
+              make test-checkstyle
+          else
+              echo "Can't find test-checkstyle target in Makefile - skipping test-checkstyle"
+          fi
 
       - name: Run API Checkstyle Scripts
         run: |
-          .github/scripts/api_checkstyle.sh
+          VPP_CRC_CHECKER="extras/scripts/crcchecker.py"
+          VPP_CRC_CHECKER_CMD="$VPP_CRC_CHECKER --check-patchset"
+
+          if [ -f $VPP_CRC_CHECKER ]; then
+              # API checker complains if the git repo is not clean.
+              # Help diagnosing those issues easier
+              git --no-pager diff
+              echo "Running $VPP_CRC_CHECKER_CMD"
+              if $VPP_CRC_CHECKER_CMD; then
+                  echo "API check successful"
+              else
+                  RET_CODE=$?
+                  echo "API check failed: ret code $RET_CODE; please read https://wiki.fd.io/view/VPP/ApiChangeProcess and discuss with ayourtch@gmail.com if unsure how to proceed"
+                  echo "::error file=.ci/scripts/vpp/crcchecker.py,line=1::API check FAILED for $GITHUB_REF. See run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+                  exit $RET_CODE
+              fi
+          else
+              echo "Cannot find $VPP_CRC_CHECKER - skipping API compatibility check"
+          fi
 
       - name: Run Commit Message Checkstyle
         run: |
-          .github/scripts/commitmsg.sh
+          if [ -f extras/scripts/check_commit_msg.sh ] ; then
+              echo "Running extras/scripts/check_commit_msg.sh"
+              extras/scripts/check_commit_msg.sh
+          else
+              echo "Cannot find cat extras/scripts/check_commit_msg.sh - skipping commit message check"
+          fi
 
       - name: Run Docs Spell
         run: |
-          .github/scripts/docs_spell.sh
+          if grep -qE '^docs\-%' Makefile && grep -qE '^spell' docs/Makefile
+          then
+              make docs-spell
+          else
+              echo "Can't find docs-spell target in Makefile - skipping docs-spell"
+          fi
 
       - name: Archive Checkstyle Logs
         if: always()
