gha(workflows/scripts): fix build and verify step
Signed-off-by: Dave Wallace <dwallacelf@gmail.com>

diff --git a/.github/workflows/vpp-build-test-merge.yml b/.github/workflows/vpp-build-test-merge.yml
--- a/.github/workflows/vpp-build-test-merge.yml
+++ b/.github/workflows/vpp-build-test-merge.yml
@@ -380,14 +380,14 @@ jobs:
           fi
 
           make_build_test() {
-              if ! make UNATTENDED=yes install-dep ; then
-                  BUILD_ERROR="FAILED 'make install-dep'"
-                  return
-              fi
-              if ! make UNATTENDED=yes install-ext-deps ; then
-                  BUILD_ERROR="FAILED 'make install-ext-deps'"
-                  return
-              fi
+          #    if ! make UNATTENDED=yes install-dep ; then
+          #        BUILD_ERROR="FAILED 'make install-dep'"
+          #        return
+          #    fi
+          #    if ! make UNATTENDED=yes install-ext-deps ; then
+          #        BUILD_ERROR="FAILED 'make install-ext-deps'"
+          #        return
+          #    fi
               if [ -f extras/scripts/build_static_vppctl.sh ]; then
                   if ! extras/scripts/build_static_vppctl.sh ; then
                       BUILD_ERROR="FAILED 'extras/scripts/build_static_vppctl.sh'"
